package(default_visibility = ["//visibility:public"])

cc_binary(
	name = "hello",
	srcs = [
		"hello.cc",
	],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
	name = "not_oops",
	srcs = ["not_oops.cc"],
)

cc_binary(
       name = "update_data",
       srcs = ["update_data.cc"],
)

cc_binary(
	name = "member_func",
	srcs = ["member_func.cc"],
)