package(default_visibility = ["//visibility:public"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
	name = "owner1",
	srcs = ["owner1.cc"],
	copts = [],
)

cc_binary(
	name = "scoped_thread",
	srcs = [
		"scoped_thread.cc",
	],
	copts = [],
)

cc_binary(
	name = "vector_thread",
	srcs = ["vector_thread.cc"],
	copts = [],
)